language: node_js

node_js:
  - "4.0"
  - "4"
  - "7"
  - "stable"

before_install:
  - yarn config set ignore-scripts true

script:
  - npm test
  - npm run lint
  - npm run build
  - npm run tsdef

cache: yarn

branches:
  except:
    - v1
