language: node_js

node_js:
  - "4.0"
  - "4"
  - "7"
  - "stable"

# before_install:
#   - yarn config set ignore-scripts true

install:
  - npm install --ignore-scripts

script:
  - npm test
  - npm run lint
  - npm run build
  - npm run tsdef

# cache: yarn
cache:
  directories:
    - node_modules

branches:
  except:
    - v1
